/* Pure technical-analysis engine. No external dependency. */
function clean(v){return Number.isFinite(Number(v))?Number(v):null}
function npSMA(v,p){return v.map((_,i)=>i<p-1?null:v.slice(i-p+1,i+1).reduce((a,b)=>a+b,0)/p)}
function npEMA(v,p){const k=2/(p+1);let e=null;return v.map((x,i)=>{e=e===null?x:x*k+e*(1-k);return i<p-1?null:e})}
function npRSI(v,p=14){const out=v.map(()=>null);if(v.length<=p)return out;let gain=0,loss=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}let ag=gain/p,al=loss/p;out[p]=al===0?100:100-100/(1+ag/al);for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;out[i]=al===0?100:100-100/(1+ag/al)}return out}
function npMACD(v,fast=12,slow=26,signal=9){const f=npEMA(v,fast),s=npEMA(v,slow);const line=v.map((_,i)=>f[i]!==null&&s[i]!==null?f[i]-s[i]:null);const cleanLine=line.map(x=>x??0),sig=npEMA(cleanLine,signal);return {macd:line,signal:sig,histogram:line.map((x,i)=>x!==null&&sig[i]!==null?x-sig[i]:null)}}
function npBollinger(v,p=20,mult=2){const mid=npSMA(v,p),upper=[],lower=[];v.forEach((_,i)=>{if(i<p-1){upper.push(null);lower.push(null);return}const w=v.slice(i-p+1,i+1),m=mid[i],sd=Math.sqrt(w.reduce((a,x)=>a+(x-m)**2,0)/p);upper.push(m+mult*sd);lower.push(m-mult*sd)});return {middle:mid,upper,lower}}
function npATR(high,low,close,p=14){const tr=close.map((c,i)=>i===0?high[i]-low[i]:Math.max(high[i]-low[i],Math.abs(high[i]-close[i-1]),Math.abs(low[i]-close[i-1])));return npSMA(tr,p)}
function npADX(high,low,close,p=14){if(close.length<p+1)return close.map(()=>null);const tr=[],plus=[],minus=[];for(let i=1;i<close.length;i++){tr.push(Math.max(high[i]-low[i],Math.abs(high[i]-close[i-1]),Math.abs(low[i]-close[i-1])));const up=high[i]-high[i-1],dn=low[i-1]-low[i];plus.push(up>dn&&up>0?up:0);minus.push(dn>up&&dn>0?dn:0)}const atr=npSMA(tr,p),ps=npSMA(plus,p),ms=npSMA(minus,p),dx=close.map(()=>null);for(let i=p-1;i<tr.length;i++){const denom=ps[i]+ms[i];dx[i+1]=denom?100*Math.abs(ps[i]-ms[i])/denom:0}return npSMA(dx.map(x=>x??0),p)}
function npTechnical(values,highs=values,lows=values){const v=values.filter(Number.isFinite),s20=npSMA(v,20),s50=npSMA(v,50),s100=npSMA(v,100),s200=npSMA(v,200),ema20=npEMA(v,20),ema50=npEMA(v,50),rsi=npRSI(v),macd=npMACD(v),bb=npBollinger(v),atr=npATR(highs,lows,v),adx=npADX(highs,lows,v),last=v.at(-1);const vals={s20:s20.at(-1),s50:s50.at(-1),s100:s100.at(-1),s200:s200.at(-1),ema20:ema20.at(-1),ema50:ema50.at(-1),rsi:rsi.at(-1),macd:macd.macd.at(-1),macdSignal:macd.signal.at(-1),macdHist:macd.histogram.at(-1),bbUpper:bb.upper.at(-1),bbMiddle:bb.middle.at(-1),bbLower:bb.lower.at(-1),atr:atr.at(-1),adx:adx.at(-1)};let score=50;const reasons=[];if(vals.s20&&last>vals.s20){score+=8;reasons.push('Price above SMA 20')}else if(vals.s20){score-=8;reasons.push('Price below SMA 20')}if(vals.s50&&last>vals.s50){score+=8;reasons.push('Price above SMA 50')}else if(vals.s50){score-=8;reasons.push('Price below SMA 50')}if(vals.ema20&&last>vals.ema20)score+=5;else if(vals.ema20)score-=5;if(vals.macdHist>0){score+=10;reasons.push('MACD momentum positive')}else if(vals.macdHist<0){score-=10;reasons.push('MACD momentum negative')}if(vals.rsi>=55&&vals.rsi<=70){score+=8;reasons.push('RSI supports momentum')}else if(vals.rsi<35){score+=4;reasons.push('RSI indicates oversold risk/rebound zone')}else if(vals.rsi>75){score-=8;reasons.push('RSI indicates overbought risk')}if(vals.adx>=25){score+=vals.macdHist>=0?5:-5;reasons.push('ADX confirms trend strength')}score=Math.max(0,Math.min(100,Math.round(score)));const signal=score>=70?'BUY':score<=35?'SELL':'HOLD';return {...vals,sma20,sma50,sma100,sma200,ema20,ema50,rsiSeries:rsi,macdSeries:macd,bbSeries:bb,atrSeries:atr,adxSeries:adx,score,signal,reasons}}
window.NEPSETechnical={sma:npSMA,ema:npEMA,rsi:npRSI,macd:npMACD,bollinger:npBollinger,atr:npATR,adx:npADX,analyze:npTechnical};
